---
- name: Update and upgrade apt on all hosts
  hosts: servers
  become: true
  tasks:
    - name: Update and upgrade apt
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
